services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transacciones-api
    restart: unless-stopped
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:5035"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      ConnectionStrings__TransaccionesConnection: "Server=sqlserver,1433;Database=DB_TRANSACCIONES;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"
    ports:
      - "80:5035"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: transacciones-sqlserver
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 1433 || exit 1"] #test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 20s
      timeout: 10s # margen al comando
      retries: 10 # Reintentamos 10 veces en lugar de 5
      start_period: 70s  # <--- CRÍTICO: No lo marques como "unhealthy" durante los primeros 40s
    volumes:
      - sqlserver_data:/var/opt/mssql #

volumes:
  sqlserver_data: