name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Reload server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 # Asegúrate de que sea el puerto de tu Droplet
          envs: JWT_SECRET_KEY,MSSQL_SA_PASSWORD
          script: |
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export MSSQL_SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}
            bash /home/buildapp/deploy.sh
